# Generated by Django 6.0.6 on 2026-06-23 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('closed_days', models.CharField(choices=[('FR', 'friday'), ('TH', 'thursday'), ('FR&TH', 'friday and thursday'), ('NO', 'no days off')], default='NO', max_length=10, verbose_name='Closed Days')),
                ('open_time', models.TimeField(verbose_name='Open time')),
                ('closed_time', models.TimeField(verbose_name='Closed time')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 'main'), (2, 'other')], verbose_name='Order')),
                ('first_follow_up_code', models.PositiveBigIntegerField(verbose_name='First Follow Up Code')),
                ('next_follow_up_code', models.PositiveBigIntegerField(verbose_name='Next Follow Up Code')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('job_type', models.CharField(choices=[('smoother', 'Smoother'), ('painter', 'Painter'), ('masker', 'Masker')], max_length=20, verbose_name='Job Type')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colleagues', to='smoothing.branch', verbose_name='Branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smoothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('landline_number', models.CharField(max_length=20, verbose_name='Landline Number')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('address', models.TextField(verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='smoothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='smoothing.smoothing'),
        ),
    ]
