# Generated by Django 6.0.6 on 2026-06-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0002_alter_smoothing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleague',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='address',
            field=models.TextField(max_length=1000, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')], verbose_name='Phone Number'),
        ),
    ]
