# Generated by Django 6.0.6 on 2026-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0003_alter_colleague_phone_number_alter_smoothing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothing',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Deactivated'), (1, 'Activated')], default=0, editable=False, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='smoothing',
            name='wallet_stock',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Wallet Stock'),
        ),
    ]
