# Generated by Django 6.0.6 on 2026-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0004_smoothing_status_smoothing_wallet_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='closed_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closed time'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Open time'),
        ),
    ]
