# Generated by Django 6.0.6 on 2026-06-29 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0005_branch_name_alter_branch_closed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothing',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Landline Number'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='smoothing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')], verbose_name='Phone Number'),
        ),
    ]
