# Generated by Django 6.0.6 on 2026-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0006_alter_smoothing_city_alter_smoothing_landline_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='first_follow_up_code',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='First Follow Up Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='next_follow_up_code',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Next Follow Up Code'),
        ),
    ]
