# Generated by Django 6.0 on 2026-07-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0007_alter_branch_first_follow_up_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoothing',
            name='user',
        ),
    ]
