# Generated by Django 6.0 on 2026-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0008_remove_smoothing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='branch',
            name='call_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Call Number'),
        ),
    ]
