# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='colleague',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='smoothing',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
    ]
