# Generated by Django 6.0 on 2026-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0010_branch_deleted_colleague_deleted_smoothing_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
