# Generated by Django 6.0 on 2026-07-12 08:10

import apps.core.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0011_smoothing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothing',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[apps.core.validations.validate_image_size_2m, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo'),
        ),
    ]
