# Generated by Django 6.0 on 2026-07-12 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0012_alter_smoothing_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='closed_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Closed time'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='open_time',
            field=models.TimeField(default=datetime.time(8, 30), verbose_name='Open time'),
        ),
    ]
