# Generated by Django 6.0 on 2026-07-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0013_alter_branch_closed_time_alter_branch_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='first_follow_up_code',
            field=models.PositiveBigIntegerField(default=0, verbose_name='First Follow Up Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='next_follow_up_code',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Next Follow Up Code'),
        ),
    ]
