# Generated by Django 6.0 on 2026-07-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0014_alter_branch_first_follow_up_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='first_follow_up_code',
        ),
    ]
