# Generated by Django 6.0.6 on 2026-06-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
        ('smoothing', '0002_alter_smoothing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smoothing.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
