# Generated by Django 6.0.6 on 2026-06-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_costumer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')], verbose_name='Phone Number'),
        ),
    ]
