# Generated by Django 6.0 on 2026-06-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_alter_costumer_phone_number'),
        ('smoothing', '0007_alter_branch_first_follow_up_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costumer',
            unique_together={('branch', 'phone_number')},
        ),
    ]
