# Generated by Django 6.0 on 2026-07-01 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_alter_costumer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='plate should like this xx-<letter>-xxx-xx', regex='^\\d{2}-.-\\d{3}-\\d{2}$')], verbose_name='Plate'),
        ),
    ]
