# Generated by Django 6.0 on 2026-07-11 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0006_car_deleted_costumer_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='plate should like this xx-<letter>-xxx-xx', regex='^\\d{2}-.*-\\d{3}-\\d{2}$')], verbose_name='Plate'),
        ),
    ]
