# Generated by Django 6.0 on 2026-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0007_car_name_alter_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Address'),
        ),
    ]
