FROM docker.arvancloud.ir/python:3.13

ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.production

WORKDIR /src

RUN apt-get update && apt-get install -y gettext && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . /src
