services:
  postgres:
    container_name: postgres_safyar
    image: postgres:18
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - safyar_postgres_data_dev:/var/lib/postgresql/18/docker
    restart: always
    ports:
      - "5432:5432"

  redis:
    container_name: redis_safyar
    image: redis:8
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - safyar_redis_data_dev:/data
    command: redis-server --appendonly yes


volumes:
  safyar_postgres_data_dev:
  safyar_redis_data_dev:

