services:
  postgres:
    container_name: postgres_safyar_prod
    image: postgres:18
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - safyar_postgres_data_prod:/var/lib/postgresql/18/docker
    restart: always
    networks:
      - safyar_network_prod

  redis:
    container_name: redis_safyar_prod
    image: redis:8
    restart: always
    volumes:
      - safyar_redis_data_prod:/data
    command: redis-server --appendonly yes
    networks:
      - safyar_network_prod

  backend:
    container_name: backend_safyar_prod
    build:
      context: ..
      dockerfile: docker/Dockerfile-prod
    env_file:
      - ../.env
    ports:
      - "${DJANGO_EXTERNAL_PORT}:8000"
    volumes:
      - "../:/src"
    restart: always
    networks:
      - safyar_network_prod
    depends_on:
      - postgres
      - redis


volumes:
  safyar_postgres_data_prod:
  safyar_redis_data_prod:

networks:
  safyar_network_prod:

