"""
Utility for deriving form-schema metadata from a DRF ModelSerializer.

The output is consumed by the frontend to render dynamic create/update forms
for any CRUD resource generated by ``weight_core.auto_generator``.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Dict, List, Optional

from django.conf import settings
from django.db import models as dj_models
from rest_framework import serializers
from apps.core.utils.api_route import get_crud_api_prefix

_AUTO_HIDDEN_FIELDS = {"id", "deleted", "created_at", "updated_at"}

# Names the API sets from auth/signals — keep in schema for detail/export but not editable in forms.
_SERVER_MANAGED_FORM_FIELD_NAMES = frozenset(
    {
        "created_by",
        "updated_by",
        "modified_by",
        "deleted_by",
        "creator",
        "modifier",
    }
)


def _resource_for_model(model: type[dj_models.Model]) -> Optional[str]:
    """
    Reproduce the prefix used in :mod:`weight.urls` so the frontend can link
    related-record selectors (FK/M2M) back to the right CRUD endpoint.
    """
    meta = model._meta
    if meta.app_label in getattr(settings, "EXCLUDE_APPS", set()):
        return None
    if model.__name__ in getattr(settings, "EXCLUDE_MODELS", set()):
        return None
    return get_crud_api_prefix(model)


def _model_field(model: type[dj_models.Model], field_name: str):
    try:
        return model._meta.get_field(field_name)
    except Exception:
        return None


def _normalize_default(default: Any) -> Any:
    """
    Convert serializer defaults into JSON-serialisable, frontend-friendly values.
    """
    if default is serializers.empty or default is None:
        return None
    if callable(default):
        try:
            value = default()
        except Exception:
            return None
    else:
        value = default
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, (str, int, float, bool, list, dict)):
        return value
    return str(value)


def _detect_input_type(
    drf_field: serializers.Field,
    model_field: Optional[dj_models.Field],
    choices: Optional[List[Dict[str, Any]]],
) -> str:
    """
    Map a DRF field plus its underlying model field to a UI input type.
    """
    if isinstance(drf_field, serializers.ManyRelatedField):
        return "multi_relation"
    if isinstance(drf_field, serializers.PrimaryKeyRelatedField):
        return "relation"
    if choices:
        if isinstance(drf_field, serializers.MultipleChoiceField) or (
            isinstance(drf_field, serializers.ListField)
            and isinstance(getattr(drf_field, "child", None), serializers.ChoiceField)
        ):
            return "multi_select"
        return "select"
    if isinstance(drf_field, serializers.BooleanField):
        return "boolean"
    if isinstance(drf_field, serializers.IntegerField):
        return "integer"
    if isinstance(drf_field, (serializers.FloatField, serializers.DecimalField)):
        return "number"
    if isinstance(drf_field, serializers.DateTimeField):
        return "datetime"
    if isinstance(drf_field, serializers.DateField):
        return "date"
    if isinstance(drf_field, serializers.TimeField):
        return "time"
    if isinstance(drf_field, serializers.EmailField):
        return "email"
    if isinstance(drf_field, serializers.URLField):
        return "url"
    if isinstance(drf_field, serializers.IPAddressField):
        return "text"
    if isinstance(drf_field, (serializers.FileField, serializers.ImageField)):
        return "file"
    if isinstance(drf_field, serializers.JSONField):
        return "json"

    if isinstance(model_field, dj_models.TextField):
        return "textarea"
    if isinstance(model_field, dj_models.GenericIPAddressField):
        return "text"
    if isinstance(model_field, dj_models.JSONField):
        return "json"

    return "text"


def _extract_choices(
    drf_field: serializers.Field,
    model_field: Optional[dj_models.Field],
) -> Optional[List[Dict[str, Any]]]:
    """
    Surface human-readable choices for select-like fields.
    """
    raw_choices = None
    if isinstance(drf_field, serializers.ChoiceField):
        raw_choices = drf_field.choices
    elif isinstance(drf_field, serializers.ListField) and isinstance(
        getattr(drf_field, "child", None), serializers.ChoiceField
    ):
        raw_choices = drf_field.child.choices
    elif model_field is not None and getattr(model_field, "choices", None):
        raw_choices = dict(model_field.choices)

    if not raw_choices:
        return None

    items: List[Dict[str, Any]] = []
    for value, label in raw_choices.items():
        items.append({"value": value, "label": str(label)})
    return items


def _relation_meta(
    drf_field: serializers.Field,
    model_field: Optional[dj_models.Field],
) -> Optional[Dict[str, Any]]:
    """
    For FK/M2M fields, return target model info so the UI can fetch options.
    """
    target_model: Optional[type[dj_models.Model]] = None
    many = False

    if isinstance(drf_field, serializers.ManyRelatedField):
        many = True
        child_relation = getattr(drf_field, "child_relation", None)
        queryset = getattr(child_relation, "queryset", None)
        if queryset is not None:
            target_model = queryset.model
    elif isinstance(drf_field, serializers.PrimaryKeyRelatedField):
        queryset = getattr(drf_field, "queryset", None)
        if queryset is not None:
            target_model = queryset.model

    if target_model is None and model_field is not None:
        related_model = getattr(model_field, "related_model", None)
        if related_model is not None:
            target_model = related_model
            many = bool(getattr(model_field, "many_to_many", False))

    if target_model is None:
        return None

    return {
        "many": many,
        "model": target_model._meta.label_lower,
        "model_name": target_model._meta.object_name,
        "verbose_name": str(target_model._meta.verbose_name),
        "resource": _resource_for_model(target_model),
    }


def _label_for(
    drf_field: serializers.Field,
    model_field: Optional[dj_models.Field],
    field_name: str,
) -> str:
    if drf_field.label:
        return str(drf_field.label)
    if model_field is not None:
        verbose = getattr(model_field, "verbose_name", None)
        if verbose:
            return str(verbose)
    return field_name.replace("_", " ").strip().title()


def _help_text_for(
    drf_field: serializers.Field,
    model_field: Optional[dj_models.Field],
) -> Optional[str]:
    if drf_field.help_text:
        return str(drf_field.help_text)
    if model_field is not None:
        text = getattr(model_field, "help_text", "")
        if text:
            return str(text)
    return None


def build_form_schema(
    model: type[dj_models.Model],
    serializer: serializers.ModelSerializer,
) -> Dict[str, Any]:
    """
    Convert a ModelSerializer into a JSON-compatible schema describing every
    writable field on the resource.
    """
    fields_meta: List[Dict[str, Any]] = []
    serializer_fields = serializer.fields

    for field_name, drf_field in serializer_fields.items():
        if field_name in _AUTO_HIDDEN_FIELDS:
            continue
        model_field = _model_field(model, field_name)
        is_auto_value = bool(
            model_field is not None
            and (
                getattr(model_field, "auto_now", False)
                or getattr(model_field, "auto_now_add", False)
            )
        )
        is_server_managed = field_name in _SERVER_MANAGED_FORM_FIELD_NAMES
        is_model_non_editable = bool(
            model_field is not None and not getattr(model_field, "editable", True)
        )
        choices = _extract_choices(drf_field, model_field)
        input_type = _detect_input_type(drf_field, model_field, choices)
        relation = _relation_meta(drf_field, model_field)

        max_length = getattr(drf_field, "max_length", None)
        min_length = getattr(drf_field, "min_length", None)
        max_value = getattr(drf_field, "max_value", None)
        min_value = getattr(drf_field, "min_value", None)

        if isinstance(max_value, Decimal):
            max_value = str(max_value)
        if isinstance(min_value, Decimal):
            min_value = str(min_value)

        decimal_places = getattr(drf_field, "decimal_places", None)
        max_digits = getattr(drf_field, "max_digits", None)

        field_meta: Dict[str, Any] = {
            "name": field_name,
            "label": _label_for(drf_field, model_field, field_name),
            "help_text": _help_text_for(drf_field, model_field),
            "input_type": input_type,
            "required": bool(drf_field.required)
            and not is_auto_value
            and not is_server_managed
            and not is_model_non_editable,
            "read_only": bool(drf_field.read_only)
            or is_auto_value
            or is_server_managed
            or is_model_non_editable,
            "write_only": bool(drf_field.write_only),
            "allow_null": bool(getattr(drf_field, "allow_null", False)),
            "allow_blank": bool(getattr(drf_field, "allow_blank", False)),
            "default": _normalize_default(getattr(drf_field, "default", None)),
        }
        if max_length is not None:
            field_meta["max_length"] = max_length
        if min_length is not None:
            field_meta["min_length"] = min_length
        if max_value is not None:
            field_meta["max_value"] = max_value
        if min_value is not None:
            field_meta["min_value"] = min_value
        if decimal_places is not None:
            field_meta["decimal_places"] = decimal_places
        if max_digits is not None:
            field_meta["max_digits"] = max_digits
        if choices is not None:
            field_meta["choices"] = choices
        if relation is not None:
            field_meta["relation"] = relation

        fields_meta.append(field_meta)

    meta = model._meta
    return {
        "model": meta.label_lower,
        "model_name": meta.object_name,
        "verbose_name": str(meta.verbose_name),
        "verbose_name_plural": str(meta.verbose_name_plural),
        "resource": _resource_for_model(model),
        "fields": fields_meta,
    }
