# Generated by Django 6.0.6 on 2026-06-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumer', '0002_costumer_branch'),
        ('smoothing', '0002_alter_smoothing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('main_part', models.CharField(max_length=50, verbose_name='Main part')),
                ('minor_part', models.CharField(max_length=70, verbose_name='Minor part')),
            ],
            options={
                'verbose_name': 'FixArea',
                'verbose_name_plural': 'FixArea',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('kilometer_of_car', models.IntegerField(verbose_name='Kilometer Of Car')),
                ('fuel_value', models.CharField(choices=[('FULL', 'Full'), ('THREE_QUARTER', 'Three Quarter'), ('HALF', 'Half'), ('ONE_QUARTER', 'One Quarter'), ('EMPTY', 'Empty')], max_length=20, verbose_name='Fuel Value')),
                ('turn_time', models.DateTimeField(blank=True, null=True, verbose_name='Turn Time')),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('TURNED', 'Turned'), ('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered')], max_length=20, verbose_name='Status')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='Fee')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='smoothing.branch', verbose_name='Branch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumer.car', verbose_name='Car')),
                ('smoothing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='smoothing.smoothing', verbose_name='Smoothing')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='FixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('fix_type', models.CharField(choices=[('SMOOTHING', 'Smoothing'), ('MASK', 'Mask'), ('PAINT', 'Paint')], max_length=20, verbose_name='Fix Type')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('number_of_days', models.PositiveSmallIntegerField(verbose_name='Number of Days')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('fix_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.fixarea', verbose_name='Fix Area')),
                ('repairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smoothing.colleague')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project.project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/project')),
                ('temporal', models.CharField(choices=[('FULL', 'Full'), ('THREE_QUARTER', 'Three Quarter'), ('HALF', 'Half'), ('ONE_QUARTER', 'One Quarter'), ('EMPTY', 'Empty')], max_length=20, verbose_name='Temporal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project', verbose_name='Project')),
            ],
        ),
    ]
