# Generated by Django 6.0 on 2026-07-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('smoothing', '0008_remove_smoothing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Main part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fixarea',
            name='minor_part',
        ),
        migrations.AddField(
            model_name='fixarea',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='smoothing.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fee',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='smoothing',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='smoothing.smoothing', verbose_name='Smoothing'),
        ),
        migrations.AlterField(
            model_name='fixarea',
            name='main_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='project.mainpart', verbose_name='Main Part'),
        ),
    ]
