# Generated by Django 6.0 on 2026-07-02 10:12

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0005_alter_car_plate'),
        ('project', '0002_mainpart_remove_fixarea_minor_part_fixarea_name_and_more'),
        ('smoothing', '0008_remove_smoothing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixitem',
            options={'verbose_name': 'FixItem', 'verbose_name_plural': 'FixItems'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'ProjectImage', 'verbose_name_plural': 'ProjectImages'},
        ),
        migrations.AddIndex(
            model_name='fixitem',
            index=models.Index(fields=['project'], name='project_fix_project_c1a2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['smoothing', 'branch'], name='project_pro_smoothi_9da19c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_pro_status_d7ebb2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_pro_created_16407c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project'], name='project_pro_project_b9d0de_idx'),
        ),
    ]
