# Generated by Django 6.0 on 2026-07-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_fixitem_options_alter_projectimage_options_and_more'),
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='smoothing.branch', verbose_name='Branch'),
        ),
    ]
