# Generated by Django 6.0 on 2026-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='temporal',
            field=models.CharField(choices=[('AF', 'After'), ('BF', 'Before')], max_length=20, verbose_name='Temporal'),
        ),
    ]
