# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectimage_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixarea',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='fixitem',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='mainpart',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
    ]
