# Generated by Django 6.0 on 2026-07-08 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_fixarea_deleted_fixitem_deleted_mainpart_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at'),
        ),
    ]
