# Generated by Django 6.0 on 2026-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectimage_created_at_projectimage_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reason_of_cancelled',
            field=models.TextField(blank=True, null=True, verbose_name='Reason Of Cancelled'),
        ),
    ]
