# Generated by Django 6.0 on 2026-07-12 07:51

from django.db import migrations
from apps.core.utils.main_part import load_main_parts

def load(*args):
    load_main_parts()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_reason_of_cancelled'),
    ]

    operations = [
        migrations.RunPython(load)
    ]
