# Generated by Django 6.0 on 2026-07-12 08:10

import apps.core.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20260712_1121'),
        ('smoothing', '0012_alter_smoothing_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='images/project', validators=[apps.core.validations.validate_image_size_10m, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('branch', 'turn_time')},
        ),
    ]
