# Generated by Django 6.0 on 2026-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Code'),
        ),
    ]
