# Generated by Django 6.0 on 2026-07-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_code'),
        ('smoothing', '0014_alter_branch_first_follow_up_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('branch', 'turn_time')},
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('branch', 'code'), ('branch', 'turn_time')},
        ),
    ]
