# Generated by Django 6.0 on 2026-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_unique_together_alter_project_code_and_more'),
        ('smoothing', '0014_alter_branch_first_follow_up_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colleagues',
            field=models.ManyToManyField(editable=False, to='smoothing.colleague', verbose_name='Colleagues'),
        ),
        migrations.AddField(
            model_name='project',
            name='mask_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Mask Days'),
        ),
        migrations.AddField(
            model_name='project',
            name='mask_price',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Mask Price'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Paint Days'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_price',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Paint Price'),
        ),
        migrations.AddField(
            model_name='project',
            name='smoothing_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Smoothing Days'),
        ),
        migrations.AddField(
            model_name='project',
            name='smoothing_price',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Smoothing Price'),
        ),
    ]
