# Generated by Django 6.0 on 2026-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_colleagues_project_mask_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fee',
        ),
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='project',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Remain Paid'),
        ),
    ]
