# Generated by Django 6.0.6 on 2026-06-23 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed.', regex='^\\d+$')], verbose_name='national code')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')], verbose_name='phone number')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('user_type', models.CharField(choices=[('SU', 'superuser'), ('OW', 'owner'), ('AD', 'admin'), ('NM', 'normal')], default='NM', max_length=10, verbose_name='User type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('submit_date', models.DateField(auto_now_add=True, help_text='for owner users', verbose_name='submit date')),
                ('status', models.CharField(choices=[('AC', 'accepted'), ('RJ', 'rejected'), ('PN', 'pending')], default='PN', max_length=2, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='account.user', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
