# Generated by Django 6.0.6 on 2026-06-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed.', regex='^\\d{10}$')], verbose_name='national code'),
        ),
    ]
