# Generated by Django 6.0.6 on 2026-06-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerrequest',
            options={'verbose_name': 'Owner Request', 'verbose_name_plural': 'Owner Requests'},
        ),
        migrations.RemoveField(
            model_name='ownerrequest',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='address',
            field=models.TextField(max_length=1000, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='shop_name',
            field=models.CharField(max_length=255, verbose_name='Shop name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='national code must have 10 characters', regex='^\\d{10}$')], verbose_name='national code'),
        ),
    ]
