# Generated by Django 6.0.6 on 2026-06-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ownerrequest_options_and_more'),
        ('smoothing', '0004_smoothing_status_smoothing_wallet_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smoothing.branch', verbose_name='Branch'),
        ),
    ]
