# Generated by Django 6.0 on 2026-07-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_branch'),
        ('smoothing', '0008_remove_smoothing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_branches',
            field=models.ManyToManyField(related_name='users', to='smoothing.branch', verbose_name='Allowed branches'),
        ),
        migrations.AddField(
            model_name='user',
            name='smoothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_user', to='smoothing.smoothing', verbose_name='Smoothing'),
        ),
    ]
