# Generated by Django 6.0 on 2026-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_allowed_branches_user_smoothing'),
        ('smoothing', '0008_remove_smoothing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='smoothing.branch', verbose_name='Allowed branches'),
        ),
    ]
