# Generated by Django 6.0 on 2026-07-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_allowed_branches'),
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='active_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smoothing.branch', verbose_name='Active branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='allowed_branches',
            field=models.ManyToManyField(related_name='users', to='smoothing.branch', verbose_name='Allowed branches'),
        ),
    ]
