# Generated by Django 6.0 on 2026-07-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_branch_user_active_branch_and_more'),
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smoothing.branch', verbose_name='Active branch'),
            preserve_default=False,
        ),
    ]
