# Generated by Django 6.0 on 2026-07-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_active_branch'),
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smoothing.branch', verbose_name='Active branch'),
        ),
    ]
