# Generated by Django 6.0 on 2026-07-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_active_branch'),
        ('smoothing', '0009_branch_address_branch_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smoothing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_user', to='smoothing.smoothing', verbose_name='Smoothing'),
        ),
    ]
