# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_smoothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
    ]
