# Generated by Django 6.0 on 2026-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_smoothing',
            field=models.BooleanField(default=True),
        ),
    ]
