# Generated by Django 6.0 on 2026-07-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_is_active_smoothing'),
        ('smoothing', '0011_smoothing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smoothing.branch', verbose_name='Active branch'),
        ),
    ]
