# Generated by Django 6.0.6 on 2026-06-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smoothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('stock', models.PositiveBigIntegerField(verbose_name='Stock')),
                ('smoothing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smoothing.smoothing', verbose_name='Smoothing')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('SU', 'Success'), ('FD', 'Failed'), ('PN', 'Pending')], max_length=2, verbose_name='Status')),
                ('transaction_type', models.CharField(choices=[('SETTLE', 'Settle'), ('WITHDRAW', 'Withdraw')], max_length=10, verbose_name='Transaction Type')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
            },
        ),
    ]
