# Generated by Django 6.0.6 on 2026-06-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoothing', '0006_alter_smoothing_city_alter_smoothing_landline_number_and_more'),
        ('wallet', '0002_wallettransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='smoothing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='smoothing.smoothing', verbose_name='Smoothing'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Wallet'),
        ),
    ]
