# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_smoothing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
    ]
