# Generated by Django 6.0 on 2026-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_deleted_wallettransaction_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_sent_empty_sms',
            field=models.BooleanField(default=False, help_text="If this be False and the stock value is empty, project will send sms to the wallet's owner", verbose_name='Is Sent Empty Sms'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_sent_warning_sms',
            field=models.BooleanField(default=False, verbose_name='Is Sent Warning'),
        ),
    ]
