# Generated by Django 6.0 on 2026-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_is_sent_empty_sms_wallet_is_sent_warning_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='stock',
            field=models.PositiveBigIntegerField(help_text='unit is Rial', verbose_name='Stock'),
        ),
    ]
