# Generated by Django 6.0 on 2026-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='tracking_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tracking code'),
            preserve_default=False,
        ),
    ]
