# Generated by Django 6.0.6 on 2026-06-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='your phone number is invalid. correct is 09xxxxxxxxx')]),
        ),
    ]
