# Generated by Django 6.0.6 on 2026-06-27 13:33

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_supportinformation_phone_number'),
    ]

