# Generated by Django 6.0.6 on 2026-06-27 13:33

from django.db import migrations

from apps.owner.models import SupportInformation


def create_support_information(*args):
    if not SupportInformation.objects.first():
        SupportInformation.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_supportinformation_phone_number'),
    ]

    operations = [
        migrations.RunPython(create_support_information)
    ]
