# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models

from apps.owner.models import SupportInformation

def create_support_information(*args):
    if not SupportInformation.objects.first():
        SupportInformation.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20260627_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportinformation',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='usagemethod',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='version',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted'),
        ),
        migrations.RunPython(create_support_information)
    ]
