# Generated by Django 6.0 on 2026-07-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_supportinformation_deleted_usagemethod_deleted_and_more'),
        ('smoothing', '0011_smoothing_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the record was saved.', verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, help_text='Whether the record was deleted.', verbose_name='Deleted')),
                ('message', models.TextField(verbose_name='Message')),
                ('sender', models.CharField(choices=[('SY', 'System'), ('SM', 'Smoothing')], max_length=2, verbose_name='Sender')),
                ('sms_type', models.CharField(choices=[('BU', 'Bulk'), ('SI', 'Single')], max_length=2, verbose_name='SMS Type')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='smoothing.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Sms Log',
                'verbose_name_plural': 'Sms Logs',
                'indexes': [models.Index(fields=['created_at'], name='owner_smslo_created_830334_idx')],
            },
        ),
    ]
