# Generated by Django 6.0 on 2026-07-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_smslog'),
        ('smoothing', '0011_smoothing_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='sender',
        ),
        migrations.AlterField(
            model_name='smslog',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='smoothing.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
