# Generated by Django 6.0 on 2026-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_smslog_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('SU', 'Success'), ('FA', 'Failed')], default='SU', max_length=2),
        ),
    ]
